### ISSUE TITLE
"CompanyId" deprecated

### ISSUE THREAD

**Issue by MarinaRomanovna** [stfbee/fastlane-plugin-rustore#5]
_C 30.07 авторизация с помощью параметра companyId будет невозможна. Используйте параметр keyId для получения токена авторизации._
<img width="891" alt="Снимок экрана 2024-07-22 в 14 30 04" src="https://github.com/user-attachments/assets/bf5ed47e-07b0-4398-a6f8-460096b71b57">

Есть ли возможность передавать keyId для плагина, чтобы не возникло проблем с публикацией в дальнейшем?

**Comment by stfbee** [comment]
Ага, асап попробую пофиксить, но до 30 числа не успею :С

**Comment by stfbee** [comment]
Спасибо @fedulvtubudul, смержил в мастер, сейчас залью на рабигемс

**Comment by stfbee** [comment]
Опубликовал 0.3.0 в рабигемс, можно обновляться
